# install: pre-commit install --hook-type pre-commit --hook-type pre-push
default_language_version:
  python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    # -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
        language_version: python3

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        args: [--py36-plus]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

- repo: local
  hooks:
      - id: pytest-check
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: black
        name: black
        entry: black .
        language: system
        pass_filenames: false
        always_run: true
      - id: mypy
        name: mypy
        entry: mypy . --install-types --non-interactive
        language: system
        pass_filenames: false
        always_run: true
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        pass_filenames: false
        always_run: true
      - id: poetry types
        name: poetry types
        entry: poetry types update
        language: system
        pass_filenames: false
        always_run: true
      - id: tox-check
        name: tox
        entry: tox
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
      - id: update examples
        name: update examples
        entry: refers -r examples/example1
        language: system
        pass_filenames: false
        always_run: true
